backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img

media_library:
  name: uploadcare
  config:
    publicKey: '9aecb324fad7f09c0c51'
  settings:
    autoFilename: true
    previewStep: true
    defaultOperations: '/smart_resize/380x380/'

public_folder: /img

collections:
  - name: 'books'
    label: 'books'
    folder: 'content/books'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publication', widget: 'datetime'  }
      - { label: 'Publish Date Format', name: 'publishformat', widget: 'select', options: ['Month and year', 'Year'], multiple: false, default: ['Month and year'], required: false }
      - { label: 'Release Date', name: 'release', widget: 'datetime' }
      - { label: 'Release Date Format', name: 'releaseformat', widget: 'select', options: ['Month and year', 'Year'], multiple: false, default: ['Month and year'], required: false }
      - { label: 'Sorting Date', name: 'sortingdate', widget: 'datetime', picker_utc: true, required: false }
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'book-page' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'ISBN', name: 'isbn', widget: 'string' }
      - { label: 'Image (max 500kb - preferable .jpg - lowercase name - no spaces)', name: post_image, widget: image, required: true, media_library: [{config: [{max_file_size: 62500}]}] }
      - { label: 'Image (max 500kb - preferable .jpg - lowercase name - no spaces square)', name: square_image, widget: image, required: true, media_library: [{config: [{max_file_size: 62500}]}] }
      - { label: 'Download link', name: 'download', widget: 'string', required: false }
      - { label: 'Download button link', name: 'download_ebook', widget: 'string', required: false }
      - { label: 'Download button name', name: 'download_name', widget: 'string', required: false }
      - { label: 'third download name', name: 'third_download_name', widget: 'string', required: false }
      - { label: 'third button', name: 'third_download', widget: 'string', required: false }
      - { label: 'Other language link', name: 'language_link', widget: 'string', required: false, hint: "this is the URL of the article in other language" }
      - { label: 'Genre', name: 'genre', widget: 'select', options: ["fiction", "short-stories", "novella", "poetry", "nonfiction", "essay", "manifesto", "autobiography"], multiple: true }
      - { label: 'Time period', name: 'time_period', widget: 'select', options: ['19th', '20th', 'victorian', 'early-modern', 'modernist', 'contemporary'], multiple: true }
      - { label: 'Theme', name: 'theme', widget: 'select', options: ["motherhood", "LGBTQ+", "politics" ,"religion", "sex-romance", "suspense-gothic", "race", "science-technology", "first-person-narrator", "banned-book", "mental-health"], multiple: true }
      - { label: 'Language', name: 'lang', widget: 'select', options: [en, es] }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Foreword & Cover', name: 'foreword', widget: 'text' }
      - { label: 'is Published?', name: 'published', widget: 'boolean', default: true, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: news
    label: News
    folder: 'content/news'
    slug: 'index'
    path: '{{title}}/index'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Language', name: 'lang', widget: 'select', options: [en, es] }
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'news-page' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: studio
    label: Studio
    folder: 'content/studio'
    slug: 'index'
    path: '{{title}}/index'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Contact email', name: 'email', widget: 'string' }
      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'Language', name: 'lang', widget: 'select', options: [en, es] }
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'studio-page' }
      - { label: 'Services', name: 'services', widget: 'list', allow_add: true }
      - { label: 'Image0', name: 'image0', widget: 'string', required: false }
      - { label: 'Image1', name: 'image1', widget: 'string', required: false }
      - { label: 'Image2', name: 'image2', widget: 'string', required: false }
      - { label: 'Image3', name: 'image3', widget: 'string', required: false }
      - { label: 'Image4', name: 'image4', widget: 'string', required: false }
      - { label: 'Image5', name: 'image5', widget: 'string', required: false }
      - { label: 'Image6', name: 'image6', widget: 'string', required: false }
      - { label: 'Image7', name: 'image7', widget: 'string', required: false }
      - { label: 'Image8', name: 'image8', widget: 'string', required: false }
      - { label: 'Image9', name: 'image9', widget: 'string', required: false }
      - { label: 'Front page block', name: 'body', widget: 'markdown' }
